### ISSUE TITLE
Area Imp Request - KoP Hall

### ISSUE THREAD

**Issue by grekan** [prophecymud/area-issues#15]
Builder Change Log:

ROOM EDITS
rnum - 2933 - Added no_recall and no_clanrecall flags
rnum - 2933 - Increased room heal and mana factor to 200/200 (botting room) (100k)
rnum - 2934 - Increased room heal and mana factor to 200/200 (botting room) (100k)
rnum - 2934 - Added no_recall and no_clanrecall flags
rnum - 2928 - Modified the extra desc on the room "tipping"
rnum - 2937 - Added more owners to the room. 
rnum - 2916 - Changed the portal room to relink to 2901 instead of 2903
rnum - 2946 - Modified the extra desc on the room "carved"

Cost: 200k (heal factor for botting rooms)

OBJECT EDITS
onum - 2952 - A small chest - I want to free up onum 2953 (the key for the chest) - Traxel's room has been open and unlocked for years, and the container itself is open and empty on live. I can now delete the vnum for the key. (Haven't yet).
onum - 2949 - Changed portal destination from Verkat Village to Asturian Rebel Camp - 2729
onum - 2963 - Changed portal destination from the Fens to Jungles of Gandahar - 59700
onum - 2921 - Changed the name of the potion to be more clear. (word of recall)
onum - 2908 - Added cure poison and cure disease to cure blindness - restrung potion but kept blindness poison and disease in the item name. (was just cure blindness)
onum - 2923 - Changed the potion spells from cure poison, cancellation, and cleanse to create food, create food, create spring. Renamed potion. (Now it's the potion of nourishment)

Cost: 0

MOB Edits:
mnum - 2906 - Added gain to the ACT options, he gain train why can't he gain convert. Definitely an oversight.

Cost: 0

MPROG EDITS

pnum - 2902 - Updated to add Dhreneval
pnum - 2906 - Updated to remove Traxel's key and add names or Xalenci's alts access Xalenci's room. 
pnum - 2916 - Edited the GRALL mprog for the mob to add new alts. 

Cost: 0

**Comment by anhegofcherek** [comment]
Live and paid for, thanks

**Comment by grekan** [comment]
Thanks!
